name: Env var Test

on:
  workflow_dispatch:

jobs:
  power-ranger:
    env:
      POWER_RANGER_ENV: "RED"  
      POWER_RANGER_ENV_2: "BLUE"
      POWER_RANGER_ENV_3: "GREEN"
      POWER_RANGER_ENV_4: "PINK"
      
    runs-on: ubuntu-24.04
    steps:
      - name: power-rangers-spd 
        env:
          KON_SA: "S.P.D"
        run: |
          echo "$KON_SA is ${POWER_RANGER_ENV} !!!"
          echo "$KON_SA is ${POWER_RANGER_ENV_2} !!!"
          echo "$KON_SA is ${POWER_RANGER_ENV_3} !!!"
          echo "$KON_SA is ${POWER_RANGER_ENV_4} !!!"
          
      - name: power-ranger-samurai
        env:
          KON_SA_2: "SAMURAI"
        run: |
          echo "$KON_SA_2 is ${POWER_RANGER_ENV} !!!"
          echo "$KON_SA_2 is ${POWER_RANGER_ENV_2} !!!"
          echo "$KON_SA_2 is ${POWER_RANGER_ENV_3} !!!"
          echo "$KON_SA_2 is ${POWER_RANGER_ENV_4} !!!"
          echo "${KON_SA} is ${POWER_RANGER_ENV} !!!"
          
  power-ranger-new:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "NEW $KON_SA is ${POWER_RANCER_ENV} !!!"
          echo "NEW $KON_SA is ${POWER_RANGER_ENV_2} !!!"
          echo "NEW $KON_SA_2 is ${POWER_RANGER_ENV_4} !!!"
          echo "NEW $KON_SA is ${POWER_RANGER_ENV} !!!"
          
          
